### ISSUE TITLE
A general question for CMAF Ingest

### ISSUE THREAD

**Issue by ggnull35** [Dash-Industry-Forum/CMAF-Conformance#58]
Hi,

I checked the spec documents and I couldnt be sure for HTTP Pull CMAF compliance.
Can Ingest source (encoder) put the chunks on storage and can CDN HTTP Pull these chunks ? 
Is this a valid approach.

Kind Regards,

**Comment by dsilhavy** [comment]
Duplicate of https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/534
